[build]
  base = "frontend/travel-story-app"
  publish = "dist"
  command = "pnpm install && pnpm run build"

[dev]
  command = "pnpm run dev"
  targetPort = 5173
  port = 8888
  framework = "vite"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200